# Generated by Django 4.2.1 on 2023-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Giocatore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="*", max_length=40)),
                ("descrizione", models.CharField(default="*", max_length=450)),
                ("portiere", models.BooleanField(default=False)),
                ("difensore", models.BooleanField(default=False)),
                ("ala_sinistra", models.BooleanField(default=False)),
                ("ala_destra", models.BooleanField(default=False)),
                ("punta", models.BooleanField(default=False)),
            ],
        ),
    ]
