# Generated by Django 4.2.1 on 2023-09-29 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Giocatore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="*", max_length=40)),
                ("descrizione", models.CharField(default="*", max_length=450)),
                ("portiere", models.BooleanField(default=False)),
                ("difensore", models.BooleanField(default=False)),
                ("ala_sinistra", models.BooleanField(default=False)),
                ("ala_destra", models.BooleanField(default=False)),
                ("punta", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eta", models.IntegerField(blank=True, null=True)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("descrizione", models.CharField(default="*", max_length=450)),
                ("portiere", models.BooleanField(default=False)),
                ("difensore", models.BooleanField(default=False)),
                ("ala_sinistra", models.BooleanField(default=False)),
                ("ala_destra", models.BooleanField(default=False)),
                ("punta", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
