# Generated by Django 4.2.1 on 2023-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partitelle", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giocatore",
            name="cognome",
        ),
        migrations.AddField(
            model_name="giocatore",
            name="ruolo",
            field=models.CharField(default="nessuno", max_length=40),
        ),
        migrations.AlterField(
            model_name="giocatore",
            name="nome",
            field=models.CharField(default="tizio", max_length=30),
        ),
    ]
