# Generated by Django 4.2.1 on 2023-08-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partitelle", "0002_remove_giocatore_cognome_giocatore_ruolo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giocatore",
            name="ruolo",
        ),
        migrations.AddField(
            model_name="giocatore",
            name="ala_destra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="giocatore",
            name="ala_sinistra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="giocatore",
            name="descrizione",
            field=models.CharField(default="*", max_length=450),
        ),
        migrations.AddField(
            model_name="giocatore",
            name="difensore",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="giocatore",
            name="portiere",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="giocatore",
            name="punta",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="giocatore",
            name="nome",
            field=models.CharField(default="*", max_length=40),
        ),
    ]
